language: node_js
node_js:
- '6'
before_install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure:
  app: maze-solver6000
  on:
    repo: RemiCarriere/Maze-Solver
